#!/bin/sh

statusLine=$(amixer get Master | tail -n 1)
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

statusLineMicrophone=$(amixer get Capture | tail -n 1)
if [[ "${status}" == "on" ]]; then
	volumeMicrophone=$(echo "${statusLineMicrophone}" | awk -F ' ' '{print $5}' | tr -d '[]%')
	MICROPHONE=$(echo "${volumeMicrophone}%">$HOME/.config/bin/.microphone )
else
	MICROPHONE=$(echo "0">$HOME/.config/bin/.microphone )
fi
BLUE=$($HOME/.config/bin/on:offBlu > $HOME/.config/bin/.on:off)
LUZ=$(brightnessctl l|grep -oP "[^\(]*%">$HOME/.config/bin/.luz )
AUDIO=$(echo "${volume}%">$HOME/.config/bin/.audio )

CHOICE=$(echo -e " LogOff\n Lock\n Coffe\n Reboot\n PowerOff"| dmenu -i -p " Power-Menu"\
    -fn fontawesome:size=13  -nb "#0E1219" -nf "#f6f6f6" -sb "#0E1219" -sf "#77D5F0")

case "$CHOICE" in
	\ Reboot)$LUZ && $AUDIO && $AUDIO && systemctl reboot;;
	\ PowerOff)$LUZ && $AUDIO && $AUDIO && systemctl poweroff -i;;
	\ LogOff)$LUZ && $AUDIO && $AUDIO && killall i3;;
	# \ Lock)~/.config/i3/script/i3lock.sh;;
	\ Lock)i3lock -i $HOME/Pictures/.wallpapers/zombi.png;;
	\ Coffe)systemctl suspend;;
esac
