#!/bin/bash
VIDEO=$HOME/Videos/$(date '+%d:%m:%Y:%H%M%S_%wx%h').mkv
MONITOR=wxga
# comando para gravar tela
# significado do comando
# ffmpeg -f x11grab -s <Resolucao> -r <Quadros Por Segundo> -i :0.0 -q:v <Qualidade de Video 1-5> <Arquivo de Saida>

if pgrep ffmpeg; then
    kill $(pgrep ffmpeg)

else
    CHOICE=$(echo -e "-\n-\n-"| dmenu -i -p "  Bluetooth: "\
    -fn fontawesome:size=13  -nb "#0E1219" -nf "#f6f6f6" -sb "#0E1219" -sf "#77D5F0")
            case "$CHOICE" in
                -)# sem audio do microfone
                    ffmpeg -f x11grab -s $MONITOR -r 25 -i :0.0 -q:v 5 $VIDEO;;
                -)# com audio do microfone
                    ffmpeg -f alsa -i pulse -f x11grab -s $MONITOR -r 25 -i :0.0 $VIDEO;;
                -)# tela segue o mouse
                    ffmpeg -f x11grab -follow_mouse 200 -s vga -i :0.0 -f alsa -i default -c:v libx264 -r 30 -c:a flac $VIDEO;;
                # )
                    #     ffmpeg -y -f x11grab -s $MONITOR -i :0.0 -f alsa -i default $VIDEO;;
                # )
                    #     ffmpeg -y -f x11grab -s $MONITOR -i :0.0 -f alsa -i default -c:v libx264 -r 30 -c:a flac $VIDEO;;
                esac

fi

# Comando pra descobrir resolucao do monitor: xdpyinfo | awk '/dimensions:/ {printf $2}''
# Código	Resolução
# sqcif  	128x96
# qcif   	176x144
# cif    	352x288
# 4cif      704x576
# 16cif     1408x1152
# qqvga  	160x120
# qvga   	320x240
# vga    	640x480
# svga   	800x600
# xga    	1024x768
# uxga   	1600x1200
# qxga   	2048x1536
# sxga   	1280x1024
# qsxga  	2560x2048
# hd1080    1920x1080
# hsxga     5120x4096
# wvga      852x480
# wxga      1366x768
# wsxga     1600x1024
# wuxga     1920x1200
# woxga     2560x1600
# wqsxga    3200x2048
# wquxga    3840x2400
# whsxga    6400x4096
# whuxga    7680x4800
# cga       320x200
# ega       640x350
# hd480	    852x480
# hd720	    1280x720
